services:
  # MySQL 服务，提供关系型数据库，用于存储结构化数据
  carBuyerAssitance-mysql:
    container_name: carBuyerAssitance-mysql
    image: mysql:9.0.1
    env_file:
      - "./env/mysql.env"
    networks:
      - carBuyerAssitance
    volumes:
      - ../config/sql:/docker-entrypoint-initdb.d
      - ./data/mysql:/var/lib/mysql

  # 你的应用服务 - 仅向外暴露此服务的端口
  carBuyerAssitance_server:
    container_name: carBuyerAssitance
    image: carbuyerassitance:latest
    ports:
      - "8080:8080"  # 仅向外暴露应用服务的端口
    networks:
      - carBuyerAssitance
    volumes:
      - ../config/:/app/config/
      - ./logs:/app/logs        # 挂载日志目录
    env_file:
      - "./env/app.env"          # 应用环境变量
    depends_on:
      -  carBuyerAssitance-mysql
    restart: unless-stopped

networks:
  carBuyerAssitance:
    driver: bridge
    name: carBuyerAssitance